@echo off
title Firmware upload
mode con cols=60 lines=10
echo 3-1. erase flash...
dfu-programmer.exe atmega32u4 erase
echo 3-2. firmware write...
dfu-programmer.exe atmega32u4 flash TCV3.hex
echo 3-3. restart device...
dfu-programmer.exe atmega32u4 reset
echo Firmware upload done.
echo press any key to continue...
pause>nul
